2022-09-16 18:03:05,528 ERROR: Exception on /edit_profile [POST] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\routes.py", line 113, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3386, in flush
    self._flush(objects)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3525, in _flush
    with util.safe_reraise():
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 3486, in _flush
    flush_context.execute()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('email', '1233342', 3)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2022-09-16 18:54:32,734 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:49]
2022-09-20 19:55:31,584 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:51]
2022-09-20 19:58:09,096 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:51]
2022-09-24 11:44:38,366 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:51]
2022-09-24 11:44:53,589 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:51]
2022-09-24 12:27:13,738 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:51]
2022-09-24 12:27:24,605 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:51]
2022-09-24 12:28:15,934 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:51]
2022-09-25 18:06:17,757 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-09-25 18:09:47,829 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-09-27 22:06:43,353 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:74]
2022-09-28 12:56:19,259 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:78]
2022-09-28 12:57:32,486 INFO: Microblog startup [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\__init__.py:78]
