2022-10-01 12:59:50,071 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 12:59:59,771 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:00:10,850 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:00:20,502 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:00:30,820 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:00:40,505 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2022-10-01 13:00:50,821 ERROR: Exception on /notifications [GET] [in C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\pchan\OneDrive\Desktop\nshi\Python\Flask\microblog\app\main\routes.py", line 193, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
